from pathlib import Path
from typing import Dict, List, Union
from urllib.parse import unquote

from pydantic import BaseModel, Field


class SeleniumCookie(BaseModel):
    # https://www.selenium.dev/selenium/docs/api/javascript/Options.Cookie.html
    name: str
    value: str
    domain: str
    expiry: int = Field(
        default=0,
        description="Unix timestamp en segundos. El valor cero indica que la cookies ya expiro o no se debe agregar al navegador.",
    )
    httpOnly: bool = False
    path: str = "/"
    sameSite: str = "None"
    secure: bool = False


def cookies_to_requests(raw: str, unquote_value=True) -> Dict[str, str]:
    """
    Convierte un header Cookie o Set-Cookie en un dict simple para requests. Esto implica unquote de los valores.

    Args:
        unquote_value (bool, optional): Decodificar los valores con unquote. Defaults to True.
    """
    # TODO: agregar set_cookie en el nombre
    cookies = {}
    # Dividir por coma solo cuando empieza una nueva cookie (key=...)
    parts = [p.strip() for p in raw.split(",")]
    for part in parts:
        segments = [s.strip() for s in part.split(";")]
        if "=" in segments[0]:
            name, value = segments[0].split("=", 1)
            cookies[name] = unquote(value) if unquote_value else value  # decodifica %xx
    return cookies


def cookies_to_selenium(raw: str, domain: str) -> List[SeleniumCookie]:
    """
    Convierte un header Cookie o Set-Cookie en el formato esperado por Selenium.
    """
    # TODO: agregar set_cookie en el nombre o un mejor indicador
    selenium_cookies = []
    parts = [p.strip() for p in raw.split(",")]
    for part in parts:
        segments = [s.strip() for s in part.split(";")]
        if "=" not in segments[0]:
            continue
        name, value = segments[0].split("=", 1)

        cookie_dict: dict = {
            "name": name,
            "value": unquote(value),
            "domain": domain,
        }

        for attr in segments[1:]:
            if "=" in attr:
                k, v = attr.split("=", 1)
                if k.lower() == "path":
                    cookie_dict["path"] = v
            else:
                # Flags sin valor: secure, httponly, etc.
                if attr.lower() == "secure":
                    cookie_dict["secure"] = "True"

                if attr.lower() == "httponly":
                    cookie_dict["httpOnly"] = True

        selenium_cookies.append(SeleniumCookie(**cookie_dict))
    return selenium_cookies


def load_netscape_cookies(filepath: Union[str, Path]) -> List[SeleniumCookie]:
    filepath = Path(filepath) if isinstance(filepath, str) else filepath
    cookies = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue  # ignorar comentarios y líneas vacías

            domain, flag, path, secure, expiration, name, value = line.split("\t")

            cookie = {
                "domain": domain,
                "path": path,
                "secure": secure.lower() == "true",
                "name": name,
                "value": value,
            }

            if expiration != "0":
                cookie["expiry"] = int(expiration)

            cookies.append(SeleniumCookie(**cookie))
    return cookies


def save_netscape_cookies(
    cookies: List[SeleniumCookie], filepath: Union[str, Path]
) -> None:
    filepath = Path(filepath) if isinstance(filepath, str) else filepath

    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by save_netscape_cookies()",
        "# Domain\tFlag\tPath\tSecure\tExpiration\tName\tValue",
    ]

    for cookie in cookies:
        domain = cookie.domain
        path = cookie.path
        secure = "TRUE" if cookie.secure else "FALSE"
        expiry = str(cookie.expiry)
        name = cookie.name
        value = cookie.value

        # flag = TRUE si el dominio empieza con ".", de lo contrario FALSE
        flag = "TRUE" if domain.startswith(".") else "FALSE"

        line = "\t".join([domain, flag, path, secure, expiry, name, value])
        lines.append(line)

    filepath.write_text("\n".join(lines), encoding="utf-8")
